import { fmtIdr } from '../db/util.js'

/**
 * HTML rendering for outgoing vendor emails.
 *
 * The model writes the prose; this wraps it in a branded, table-based layout with a
 * structured summary of the request. The facts in that summary come from Node's own
 * database row — never re-parsed out of the model's text — so the numbers a vendor reads
 * are always the stored ones. Every interpolated value is HTML-escaped: the body is
 * model-generated text and must never be trusted as markup.
 */

export interface PartRequestEmailMeta {
  requestCode: string
  partName: string
  machine: string
  vendor: string
  costIdr: number
  checksheet?: string
  finding?: string
  note?: string | null
  autoApproved?: boolean
}

function esc(s: unknown): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/** Plain-text body -> HTML paragraphs, preserving the model's line breaks. */
function paragraphs(body: string): string {
  return body
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter(Boolean)
    .map(
      (block) =>
        `<p style="margin:0 0 14px;font-size:14px;line-height:1.65;color:#333333;">${esc(block).replace(
          /\n/g,
          '<br>',
        )}</p>`,
    )
    .join('')
}

function row(label: string, value: string, opts: { strong?: boolean } = {}): string {
  const weight = opts.strong ? '600' : '400'
  const color = opts.strong ? '#333333' : '#5d646e'
  return `<tr>
    <td style="padding:7px 0;font-size:12px;color:#8b929b;white-space:nowrap;">${esc(label)}</td>
    <td style="padding:7px 0;font-size:13px;font-weight:${weight};color:${color};text-align:right;">${esc(value)}</td>
  </tr>`
}

export function renderPartRequestEmail(body: string, meta: PartRequestEmailMeta): string {
  const badge = meta.autoApproved
    ? `<span style="display:inline-block;padding:3px 10px;border-radius:99px;background:#ecf4ed;color:#196b24;font-size:11px;font-weight:600;">Auto-approved · below threshold</span>`
    : `<span style="display:inline-block;padding:3px 10px;border-radius:99px;background:#edf4f8;color:#156082;font-size:11px;font-weight:600;">Approved by supervisor</span>`

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${esc(meta.partName)} — ${esc(meta.machine)}</title>
</head>
<body style="margin:0;padding:24px 12px;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;margin:0 auto;background:#ffffff;border:1px solid #e0e0e0;border-radius:12px;overflow:hidden;">
    <tr>
      <td style="background:#156082;padding:18px 24px;">
        <div style="font-size:17px;font-weight:700;color:#ffffff;letter-spacing:-0.2px;">SmartPM</div>
        <div style="font-size:12px;color:#b5d0df;margin-top:2px;">PT Mattel Indonesia · Preventive Maintenance</div>
      </td>
    </tr>
    <tr>
      <td style="padding:24px;">
        <div style="margin-bottom:16px;">${badge}</div>
        ${paragraphs(body)}
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:20px;border-top:1px solid #e0e0e0;padding-top:4px;">
          <tr>
            <td colspan="2" style="padding:14px 0 4px;font-size:11px;font-weight:700;letter-spacing:0.6px;text-transform:uppercase;color:#8b929b;">Request summary</td>
          </tr>
          ${row('Request ID', meta.requestCode)}
          ${row('Part', meta.partName, { strong: true })}
          ${row('Machine', meta.machine)}
          ${meta.finding ? row('Finding', meta.finding) : ''}
          ${meta.checksheet ? row('Source checksheet', meta.checksheet) : ''}
          ${meta.note ? row('Recurrence', meta.note) : ''}
          ${row('Estimated cost', fmtIdr(meta.costIdr), { strong: true })}
        </table>
      </td>
    </tr>
    <tr>
      <td style="background:#f5f5f5;border-top:1px solid #e0e0e0;padding:14px 24px;">
        <p style="margin:0;font-size:11px;line-height:1.6;color:#8b929b;">
          Automated request generated by SmartPM for ${esc(meta.vendor)}.
          Estimated cost is from the PTMI part catalogue and is not a purchase order.
        </p>
      </td>
    </tr>
  </table>
</body>
</html>`
}

export interface ConsolidatedPoEmailMeta {
  vendor: string
  /** Part-request codes covered by this single purchase order. */
  lineItems: Array<{ code: string; part: string; machine: string; costIdr: number }>
  totalIdr: number
}

/**
 * Branded HTML for one consolidated purchase order covering several part requests.
 *
 * Same rule as the single-request email: the model writes the prose, but every line item
 * and the total come from Node's own rows, so the figures a vendor reads are the stored
 * ones. All interpolation is escaped — the body is model output and is not trusted markup.
 */
export function renderConsolidatedPoEmail(body: string, meta: ConsolidatedPoEmailMeta): string {
  const lines = meta.lineItems
    .map(
      (li) => `<tr>
        <td style="padding:7px 0;font-size:12px;color:#8b929b;white-space:nowrap;">${esc(li.code)}</td>
        <td style="padding:7px 8px;font-size:13px;color:#333333;">${esc(li.part)}<div style="font-size:11px;color:#8b929b;">${esc(li.machine)}</div></td>
        <td style="padding:7px 0;font-size:13px;color:#333333;text-align:right;white-space:nowrap;">${esc(fmtIdr(li.costIdr))}</td>
      </tr>`,
    )
    .join('')

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Consolidated purchase order — ${esc(meta.vendor)}</title>
</head>
<body style="margin:0;padding:24px 12px;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;margin:0 auto;background:#ffffff;border:1px solid #e0e0e0;border-radius:12px;overflow:hidden;">
    <tr>
      <td style="background:#156082;padding:18px 24px;">
        <div style="font-size:17px;font-weight:700;color:#ffffff;letter-spacing:-0.2px;">SmartPM</div>
        <div style="font-size:12px;color:#b5d0df;margin-top:2px;">PT Mattel Indonesia · Preventive Maintenance</div>
      </td>
    </tr>
    <tr>
      <td style="padding:24px;">
        <div style="margin-bottom:16px;">
          <span style="display:inline-block;padding:3px 10px;border-radius:99px;background:#edf4f8;color:#156082;font-size:11px;font-weight:600;">
            Consolidated purchase order · ${meta.lineItems.length} item${meta.lineItems.length === 1 ? '' : 's'}
          </span>
        </div>
        ${paragraphs(body)}
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:20px;border-top:1px solid #e0e0e0;">
          <tr>
            <td colspan="3" style="padding:14px 0 4px;font-size:11px;font-weight:700;letter-spacing:0.6px;text-transform:uppercase;color:#8b929b;">Line items</td>
          </tr>
          ${lines}
          <tr>
            <td colspan="2" style="border-top:1px solid #e0e0e0;padding:10px 0 0;font-size:12px;font-weight:600;color:#333333;">Total</td>
            <td style="border-top:1px solid #e0e0e0;padding:10px 0 0;font-size:14px;font-weight:700;color:#333333;text-align:right;white-space:nowrap;">${esc(fmtIdr(meta.totalIdr))}</td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td style="background:#f5f5f5;border-top:1px solid #e0e0e0;padding:14px 24px;">
        <p style="margin:0;font-size:11px;line-height:1.6;color:#8b929b;">
          Automated consolidated request generated by SmartPM for ${esc(meta.vendor)}.
          Estimated costs are from the PTMI part catalogue and are not a purchase order.
        </p>
      </td>
    </tr>
  </table>
</body>
</html>`
}
